version: '3'
services:
    ganache:
        image: '0xorg/ganache-cli:6.4.1'
        ports:
            - '8545:8545'
        environment:
            VERSION: 6.6.0
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=api
        ports:
            - '5432:5432'
