# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.12.0-browsers
            - image: postgres

        working_directory: ~/repo
        environment:
            ETHEREUM_RPC_URL: http://localhost:8545
            CHAIN_ID: 1337
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - run: yarn build
            - run: yarn lint
            - run: yarn prettier
            - run: yarn test
