[profile.default]
src = 'src'
out = 'foundry-artifacts'
test = 'test/foundry'
libs = ["lib"]
remappings = [
    '@0x/contracts-utils/=../node_modules/@0x/contracts-utils/',
    '@0x/contracts-erc20/=../node_modules/@0x/contracts-erc20/',
    '@0x/contracts-zero-ex/=../node_modules/@0x/contracts-zero-ex/'
]
allow_paths = ["../node_modules"]
cache_path = 'foundry-cache'
optimizer_runs = 1000000