name: Deploy
on:
    issue_comment:
        types: [created, edited]
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy from branch to staging
              if: github.event.issue.pull_request && github.event.comment.body == 'deploy staging'
              run: echo "folder=staging" >> $GITHUB_ENV
            - name: deploy from branch to production
              if: github.event.issue.pull_request && github.event.comment.body == 'deploy production'
              run: echo "folder=prod" >> $GITHUB_ENV
            - name: deploy from master to production
              if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
              run: echo "folder=prod" >> $GITHUB_ENV
            - run: echo Deploying to ${{ env.folder }} from branch $GITHUB_REF at $GITHUB_SHA
            - name: Checkout 0x-main-infra
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PAT }}
                  repository: 0xProject/0x-main-infra
            - name: Update API configs
              run: sed -i -e 's/"883408475785\.dkr\.ecr\.us-east-1\.amazonaws\.com\/0x\/api\:.*"/"883408475785\.dkr\.ecr\.us-east-1\.amazonaws\.com\/0x\/api\:${{ github.sha }}"/g' env/0x-api/${{ env.folder }}/common/*.yml env/0x-api/${{ env.folder }}/apis/*.yml
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3.5.0
              with:
                  token: ${{ secrets.PAT }}
                  commit-message: '0x-api/${{ env.folder }}: Deploy ${{ github.sha }}'
                  title: '[0xApi][${{ env.folder }}] Deploy ${{ github.ref }}'
                  branch: '0xApi/${{ env.folder }}/${{ github.ref }}'
                  body: |
                      PR: ${{ github.event.issue.url }}
                      SHA: https://github.com/${{ github.repository }}/tree/${{ github.sha }}
                      Comparison: https://github.com/${{ github.repository }}/compare/master...${{ github.ref}}
            - name: Check outputs
              run: |
                  echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
